### ISSUE TITLE
dashboard: when property is not available

### ISSUE THREAD

**Issue by augustogoncalves** [Developer-Autodesk/forge.learning#84]
when a property is not found, it shows a popup, [as code here](https://github.com/Developer-Autodesk/forge.learning/blob/master/docs/viewer/dashboard/panelbasics.md#dashboardpaneljs).

[at the end](https://github.com/Developer-Autodesk/forge.learning/blob/master/docs/viewer/dashboard/charts.md) of the tutorial, we need some troubleshooting describing how to handle this alert.

**Comment by dukedhx** [comment]
@augustogoncalves do you want me to get a PR out for this?

**Comment by augustogoncalves** [comment]
thanks @dukedhx , just had some spare time to fix it :)
